version: "3.9"

services:
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=YjJiOTY0NDAxNWRkNmI1Y2Yx
    stdin_open: true
    tty: true
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: secure-x-db
      POSTGRES_USER: secure-x
      POSTGRES_PASSWORD: secure-x
    ports:
      - "5432:5432"
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: secure-x-db
      DB_USERNAME: secure-x
      DB_PASSWORD: secure-x
      RABBITMQ_USER: admin
      RABBITMQ_PASS: YjJiOTY0NDAxNWRkNmI1Y2Yx
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
  rabbitmqdata: {}